apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  labels:
    name: color-api-pod
spec:
  containers:
  - name: color-api-pod
    image: marcos1503/color-api:1.2.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 3000
    env:
      - name: DELAY_STARTUP
        value: "false"
      - name: FAIL_LIVENESS
        value: "true"
    startupProbe: # Startup probe (hits /up to confirm the app finished booting)
      httpGet:
        path: /up
        port: 3000
      failureThreshold: 2
      periodSeconds: 3
    livenessProbe: # Liveness probe (hits /health to confirm it stays healthy)
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 3
      periodSeconds: 10
      failureThreshold: 3


