apiVersion: apps/v1
kind: Pod
metadata:
  name: sole-nginx
  labels:
    app: nginx
  annotations:
    description: "This is an nginx pod for learning"
    version: "1.0"
spec:
  containers:
  - name: nginx
    image: nginx:1.27.0
    ports:
    - containerPort: 80