apiVersion: v1
kind: Pod
metadata:
  name: color-api
  name:space: dev
  labels:
    app: color-api
spec:
  containers:
  - name: color-api
    image: marcos1503/color-api:1.0.0
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
