apiVersion: v1
kind: Pod
metadata:
  name: heavy-api
  name:space: dev
  labels:
    app: heavy-api
spec:
  containers:
  - name: heavy-api
    image: marcos1503/color-api:1.0.0
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    ports:
    - containerPort: 80
