apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "2"      # Twice the dev allocation
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi