apiVersion: v1
kind: Service
metadata:
  name: color-api-node-port
  labels:
    app: color-api
spec:
  type: NodePort
  selector:
    app: color-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      name: http
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30081
      name: api 
  