apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-satateful-set
spec:
  selector:
    matchLabels:
      app: busybox
  serviceName: busybox
  replicas: 2
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: local-vol
        image: busybox:latest
        command:
        - 'sh'
        - '-c'
        - 'sleep 3600'
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: local-volume
          mountPath: /mnt/local
  volumeClaimTemplates:
  - metadata:
      name: local-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi