apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
spec:
  type: NodePort
  selector:
    app: api-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007 