apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo
  labels:
    app.kubernetes.io/name: empty-dir-demo
spec:
  containers:
  - name: empty-dir-writer
    image: busybox:latest
    command:
    - 'sh'
    - '-c'
    - 'sleep 3600'
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: empty-dir-volume
      mountPath: /usr/share/empty-dir
  - name: empty-dir-reader
    image: busybox:latest
    command:
    - 'sh'
    - '-c'
    - 'sleep 3600'
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: empty-dir-volume
      mountPath: /usr/share/empty-dir
      readOnly: true
  volumes:
  - name: empty-dir-volume
    emptyDir: {}
