apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
  labels:
    app: color-api
    environment: local
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-api
      environment: local
      tier: backend
    matchExpressions:
      - key: managed
        operator: Exists
      # Optional extra example:
      # - key: tier
      #   operator: In
      #   values: ["backend", "cache"]
  template:
    metadata:
      labels:
        app: color-api
        environment: local
        tier: backend
        managed: "true"     # Critical for the Exists operator
    spec:
      containers:
      - name: color-backend
        image: marcos1503/color-api:1.1.0
        ports:
        - containerPort: 80