apiVersion: v1
kind: Pod
metadata:
  name: traffic-gen
  labels:
    app: traffic-gen
spec:
  containers:
  - name: traffic-gen
    image: marcos1503/traffic-gen:1.0.0
    args:
    - 'color-api-svc.dev.svc.cluster.local'
    - '1'
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  